COMPONENT_TYPE_CONTAINER = "CONTAINER";
COMPONENT_TYPE_TEXT = "TEXT";
COMPONENT_TYPE_COMMAND_LIST = "COMMAND_LIST";
COMPONENT_TYPE_COMMAND = "COMMAND";
COMPONENT_TYPE_FORM = "FORM";
COMPONENT_TYPE_INPUT = "INPUT";
COMPONENT_TYPE_THUMBNAIL = "THUMBNAIL";
COMPONENT_TYPE_CAROUSEL = "CAROUSEL";