CONNECT_REQUEST = "CONNECT_REQUEST";
CONNECT_RESPONSE = "CONNECT_RESPONSE";

DISCONNECT_REQUEST = "DISCONNECT_REQUEST";
DISCONNECT_RESPONSE = "DISCONNECT_RESPONSE";

TERMINAL_REQUEST = "TERMINAL_REQUEST";
API_RESPONSE = "API_RESPONSE";

API_RESPONSE_CHANGE_COMPONENT = "API_RESPONSE_CHANGE_COMPONENT";
